# Generated by Django 5.2.5 on 2025-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
    ]
