# Generated by Django 5.2.5 on 2025-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Help & Manual',
                'verbose_name_plural': 'Help & Manual',
            },
        ),
    ]
