# Generated by Django 5.2.5 on 2025-08-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_helpplaceholder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpPlaceholder',
        ),
    ]
