# Generated by Django 5.2.5 on 2025-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0009_delete_helpplaceholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='img_url_for_about',
            field=models.URLField(blank=True, null=True),
        ),
    ]
