# Generated by Django 5.2.5 on 2025-08-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0010_aboutme_img_url_for_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Our Service', 'verbose_name_plural': 'Our Services'},
        ),
    ]
