# Generated by Django 5.2.5 on 2025-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0011_alter_services_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_logo', models.URLField()),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Main Page Landing Section',
            },
        ),
    ]
