# Generated by Django 5.2.5 on 2025-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0012_herosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='brand_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
