# Generated by Django 5.2.5 on 2025-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0013_herosection_brand_name_herosection_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
