# Generated by Django 5.2.5 on 2025-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0014_herosection_favicon_url_herosection_hero_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='favicon_url',
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_name_description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Optional Field'),
        ),
    ]
