# Generated by Django 5.2.5 on 2025-08-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0015_remove_herosection_favicon_url_herosection_hero_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
