# Generated by Django 5.2.5 on 2025-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0017_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
