# Generated by Django 5.2.5 on 2025-08-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0019_servicefeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefeature',
            old_name='feature',
            new_name='feature_text',
        ),
    ]
